### ISSUE TITLE
Result score string

### ISSUE THREAD

**Issue by motss** [MeTaNoV/gold-password-input#1]
Please consider adding a public property to customize user's own strings for the result's score inside `gold-password-input-strength-meter` instead of just showing weak or strong.

**Comment by GeoloeG-IsT** [comment]
Good idea! I will work on it ASAP.

**Comment by motss** [comment]
:smile:

**Comment by GeoloeG-IsT** [comment]
done! feel free to report any problems! With this comes v1.0.0! :)
