### ISSUE TITLE
Update toggle-icon to v1.1

### ISSUE THREAD

**Issue by JosefJezek** [MeTaNoV/gold-password-input#11]
https://github.com/fxedel/toggle-icon/releases

**Comment by GeoloeG-IsT** [comment]
this is an issue in the current versioning of toggle-icon: https://github.com/fxedel/toggle-icon/issues/5

**Comment by fxedel** [comment]
toggle-icon's versioning is now fixed ;-)

**Comment by GeoloeG-IsT** [comment]
thanks @fxedel ! :)
