### ISSUE TITLE
Remove default import of gold-password-input-strength-meter.html

### ISSUE THREAD

**Issue by JosefJezek** [MeTaNoV/gold-password-input#12]
Could you remove this import from `gold-password-input.html`.  I would like to add this import on demand in custom element when I apply `strength-meter` attribute.

`<link rel="import" href="./gold-password-input-strength-meter.html">`

`bower_components/zxcvbn/dist/zxcvbn.js` have `801KB` :-(

**Comment by GeoloeG-IsT** [comment]
done, I will do a new release in a few minutes! (implementation is a bit different)
