### ISSUE TITLE
Toggle icon issue

### ISSUE THREAD

**Issue by JosefJezek** [MeTaNoV/gold-password-input#13]
Toggle icon don't change icon...

![image](https://cloud.githubusercontent.com/assets/2110319/16355380/1b212c1a-3ab5-11e6-9e60-37c1be1860e4.png)

**Comment by fxedel** [comment]
Did you already try the latest toggle-icon version 1.1.1? Are there error messages in the console?

**Comment by JosefJezek** [comment]
Yes, I am trying latest version 1.1.1. Console is without errors.

Demo is here https://pwa-demo.appspot.com/sign-in/sign-in-with-email

https://github.com/StartPolymer/progressive-web-app-template/blob/master/src/app-pages/app-pages-sign-in/app-page-sign-in-with-email/app-page-sign-in-with-email.html#L58-L63

**Comment by GeoloeG-IsT** [comment]
looks like the transform is being applied but no change of icon... @fxedel can you check your last fix? it was working properly in 1.1.0! :)

**Comment by fxedel** [comment]
First, I couldn't see what your problem is as it worked fine for me. But then I figured out that this is a browser issue – Firefox 47 works fine and changes the icon while Chromium 50 doesn't. I'm working on fixing this.

**Comment by GeoloeG-IsT** [comment]
this is weird because my demo page is working on chrome... I'll take a closer look also!

**Comment by fxedel** [comment]
It seems to be a styling issue. This is the relevant CSS rule: https://github.com/fxedel/toggle-icon/blob/5128b158ae8926a2d8dedd39776e75f0d2f9ae77/toggle-icon.html#L90-94

**Comment by fxedel** [comment]
I've found the issue. In your demo, the native shadow dom (there's an `#shadow-root` in the dev console) is used. But for some reason, the CSS selector `:host[checked]` didn't work. After adding parentheses (`:host([checked])`), which also works without using the native shadow dom and in Firefox, the rule was applied.

**Comment by fxedel** [comment]
Try version 1.1.2.

**Comment by JosefJezek** [comment]
Toggle icon is now ok. Thank you :+1:

**Comment by GeoloeG-IsT** [comment]
thx @fxedel !
