### ISSUE TITLE
Tabindex issue

### ISSUE THREAD

**Issue by gabrielle-perez-movile** [MeTaNoV/gold-password-input#18]
I am trying to create a user login inside a `paper-dialog`, but the tab index is ignored...

```
<div>
    <paper-input id="supervisorUsername" type="text"  required tabindex="0"></paper-input>
    <gold-password-input id="supervisorPassword" reveal type="password" required tabindex="0"></gold-password-input>
</div>
```

I already tried with `tabindex="5"` for the gold element but nothing happens... is it a bug or am I doing something wrong?

**Comment by GeoloeG-IsT** [comment]
Hi @gabrielle-perez-movile , thanks for reporting, let me take a look at that a bit later!

**Comment by GeoloeG-IsT** [comment]
Hi @gabrielle-perez-movile, sorry for the delay... 
Since `tabindex` is a host attribute, it would require you to have the following syntax : `tabindex$="5"`. Can you told me if this solved your issue?

**Comment by GeoloeG-IsT** [comment]
Same as for the `paper-input`: https://github.com/PolymerElements/paper-input/pull/489

**Comment by GeoloeG-IsT** [comment]
closing, @gabrielle-perez-movile, tell me if you still have the issue?
