### ISSUE TITLE
Reverse show icon logic

### ISSUE THREAD

**Issue by JosefJezek** [MeTaNoV/gold-password-input#19]
In Google My account change password page is show eye icon logic reversed...

Could you change icon?

![image](https://cloud.githubusercontent.com/assets/2110319/18005594/26b9723c-6b9b-11e6-937a-544930c21878.png)

**Comment by JosefJezek** [comment]
And please change color of icon to gray color...

**Comment by MeTaNoV** [comment]
@JosefJezek which gray is it?

**Comment by GeoloeG-IsT** [comment]
done in 1.1.5 

Sorry for the delay...
