### ISSUE TITLE
zxcvbn.js not included in polymer build (with polymer-cli)

### ISSUE THREAD

**Issue by srijken** [MeTaNoV/gold-password-input#20]
We're running into a problem with unbundled build result (of `polymer build`)

Right here it dynamically attempts to load zxcvbn: https://github.com/MeTaNoV/gold-password-input/blob/master/gold-password-input-strength-meter.html#L171

`polymer build` doesn't include the javascript for zxcvbn, so that request fails.

**Comment by GeoloeG-IsT** [comment]
I will document the component for the user to add the dependency to the polymer.json configuration file like follow:

`
  "includeDependencies": [
    "bower_components/zxcvbn/dist/zxcvbn.js"
  ]
`

Did you choose this solution for your own need?

**Comment by GeoloeG-IsT** [comment]
@srijken did you try with `includeDependencies`?
