### ISSUE TITLE
Required Strength validator

### ISSUE THREAD

**Issue by bennypowers** [MeTaNoV/gold-password-input#22]
I'd like to declare a minimum strength like so
```html
<gold-password-input
  strength-meter
  min-strength="medium">
</gold-password-input>
```

**Comment by GeoloeG-IsT** [comment]
Quite straightforward! :) I will take care of it as soon as I have more time... 
You can provide your own version as PR if you got more time than me! :) Else, I will ask you for a bit of patience...

**Comment by bennypowers** [comment]
Ok I might put something together I hacked an implementation in the parent that looks like this

```js
_computeRegisterDisabled: function (email, password) {
  if (this.$.password.$$('#strength')) {
    var emailTouched = email !== "";
    var emailValid = !this.$.email.invalid;
    var passwordStrong = this.$.password.$$('#strength')._strengthMeterScore === 'Strong';
    var passwordVeryStrong = this.$.password.$$('#strength')._strengthMeterScore === 'VeryStrong';
    return !( emailTouched && emailValid && ( passwordStrong || passwordVeryStrong ) );
  } else {
    return true;
  }
}
```

I think the best thing to do is to redefine password strength as a number, so we could validate like `strength > 2`

**Comment by RoXuS** [comment]
hello, I do this on my fork, it works great but I use several es6 feature -> https://github.com/RoXuS/gold-password-input/commit/a204c31dfdaa3c724012f350f8159d9bb94f8727

If you are interested...

**Comment by GeoloeG-IsT** [comment]
Ongoing PR here: https://github.com/GeoloeG/gold-password-input/pull/26

**Comment by GeoloeG-IsT** [comment]
@bennypowers , thanks to @RoXuS , you can test this feature in the upcoming release!
