### ISSUE TITLE
Polymer 2 support

### ISSUE THREAD

**Issue by hyyan** [MeTaNoV/gold-password-input#23]
Is the element ready to be used with Polymer 2?!!

**Comment by hyyan** [comment]
Any update soon in order to make the element works with Polymer 2 ?

**Comment by cordovapolymer** [comment]
@MeTaNoV any update on this?

**Comment by GeoloeG-IsT** [comment]
I'll try to bring support for Polymer 2.0 for this component as well as my others before the Summit in Copenhagen.

**Comment by bennypowers** [comment]
@MeTaNoV Thanks for the sweet component. Would you please update it for paper-input 1 - 2? and polymer 1 - 2?

**Comment by hyyan** [comment]
+1

**Comment by GeoloeG-IsT** [comment]
@hyyan @bennypowers , I just found some time to work on the 2.0 implementation of the component. It seems to work for the purpose of the demo. Could you give me your feedback for your own use-case? Thanks!
