### ISSUE TITLE
Strength meter as progress bar

### ISSUE THREAD

**Issue by xelra** [MeTaNoV/gold-password-input#27]
It would be great if it were possible to also have the strength meter as a progress bar where the line is.

My suggestion is to start out in blue on focus, just like it is now. Then have a progress line come in from the left, while you type. Ideally that line also changes color according to the strength meter colors and hits 100% once "very strong" has been reached.

**Comment by xelra** [comment]
This element https://www.webcomponents.org/element/PolymerElements/paper-progress could be a great inspiration.

**Comment by GeoloeG-IsT** [comment]
For this feature, do you want the progress bar in addition to the current labels or instead?
I'll try to tinker with both case, by adding a property `useLabel` which default to `true` to display the labels and a property 'useProgressBar' which default to `false` to use the progress bar so it can fit all 3 use-cases.

**Comment by GeoloeG-IsT** [comment]
@xelra , you can check master for the first implementation of a progress bar. You just have to add `use-progress` as an attribute. Optionally, you can now also hide the labels using `no-label` attribute.
Tell me what you think.

**Comment by xelra** [comment]
The progress bar works very well. It behaves exactly as intended.

I was hoping though that it wouldn't be an extra element, but instead replace/overlay the original underline. So that it doesn't add any additional height.

When I requested the feature I had something like this in mind:
- Click the input: everything is as it is now.
- Start typing: The underline turns into a progress bar with the same styling.
- Keep typing: The underline fills up as you type.
- Reach "Very Strong": The underline and the complete input now look as if nothing ever happened, only that it is colored green.

What do you think about that?

**Comment by GeoloeG-IsT** [comment]
That would be nice to have, indeed. Let me see if the underlying structure enables me to do that!

**Comment by GeoloeG-IsT** [comment]
@xelra , I managed to find a way to implement that behavior, can you test master to see if this is working for you?

**Comment by xelra** [comment]
It works amazingly and it is beautiful. I've tested it in multiple browsers, on mobile and I've also tested the dynamic with switching between error and valid. 

I couldn't find any bugs.

Great work!

**Comment by GeoloeG-IsT** [comment]
Glad to hear, let's close this issue then! :)
