### ISSUE TITLE
Option to disable info icon

### ISSUE THREAD

**Issue by xelra** [MeTaNoV/gold-password-input#28]
It would be great if the info icon of the strength meter could be disabled.

**Comment by GeoloeG-IsT** [comment]
@xelra If I understand, do you want me to add an option to hide the icon but still keep the tooltip?

**Comment by xelra** [comment]
Yes, actually I think both are desirable. I could already achieve hiding the icon by setting `display: none` to it, but the tooltip would still show.
It would be great if all 3 cases could be accomodated (personally I'm not a fan of the info icon at all, but I'm sure some users love them).

My app is multi-language and since https://github.com/dropbox/zxcvbn/pull/124 hasn't been merged for almost 2 years now, I'm not having high hopes. So I need to be able to disable the tooltip completely.

**Comment by GeoloeG-IsT** [comment]
@xelra , I refactored the tooltip to appear on the icon only and added a property `disableTooltip`, so that I don't clutter too much the component with 2 properties.
