### ISSUE TITLE
Upstream issue with clipping error messages

### ISSUE THREAD

**Issue by xelra** [MeTaNoV/gold-password-input#29]
When using `golden-password-input` I have the same problem as with `paper-input`. The error messages get clipped, because the contained `paper-input-container` has only `8px` padding on the bottom, but the error message needs `20px`.
It looks like this
![image](https://user-images.githubusercontent.com/908568/33521222-4d1b9420-d7cc-11e7-8a5c-d00be58fe911.png)

The first two inputs are `paper-input-container` elements that I've applied these fixes to
```
paper-input-container {
	padding-top: 0px;
	padding-bottom: 20px;
}
```
The third input is a `gold-password-input`.

Sadly I cannot apply this fix for `gold-password-input` as well as `paper-input` though.

**Comment by xelra** [comment]
I have identified the problem. `<paper-input-container>` is styled with `overflow: hidden`, which breaks the inheritance chain of visible overflow. Changing it to `overflow: inherit` or completely removing it from `:host {}` should fix the issue.

EDIT:
So for everyone who is wondering how to properly fix this in the meantime. Just put the following CSS mixin in your component, where you're using the input. It will style the `paper-input-container` in your Shadow DOM.
```
:host {
	--paper-input-container: {
		overflow: inherit;
	}
}
```

**Comment by xelra** [comment]
This issue has been fixed upstream and will soon make it into release. 

https://github.com/PolymerElements/paper-input/pull/598

**Comment by GeoloeG-IsT** [comment]
I was aware of this one as of #4 .

Great that it has been fixed upstream!
