### ISSUE TITLE
Focus outline when clicking certain areas

### ISSUE THREAD

**Issue by xelra** [MeTaNoV/gold-password-input#31]
![untitled](https://user-images.githubusercontent.com/908568/33634231-ce90d6e8-da13-11e7-9c23-dedd01669ebf.png)

When clicking certain areas of the input field, like the whitespaces around the label or the error message, it is possible to focus the element and get this ugly outline.

**Comment by xelra** [comment]
I've identified the issue. It's the outline directly on the gold-password-input itself. So it either needs an `outline: inherit;` or an `outline: none;` in `:host{}`.

In the meantime, anyone encountering this issue can just put the following code in the parent element.
```
gold-password-input {
	outline: inherit;
}
```

**Comment by GeoloeG-IsT** [comment]
well spotted and thanks for the solution!
