### ISSUE TITLE
Neon animation not working

### ISSUE THREAD

**Issue by xelra** [MeTaNoV/gold-password-input#32]
I'm getting this error when the tooltip of the info icon opens/closes:
```
Couldnt play ( fade-out-animation ). ReferenceError: KeyframeEffect is not defined
    at HTMLElement.configure (fade-out-animation.html:39)
    at HTMLElement._configureAnimations (neon-animation-runner-behavior.html:32)
    at HTMLElement.playAnimation (neon-animation-runner-behavior.html:92)
    at HTMLElement.hide (paper-tooltip.html:295)
    at HTMLSpanElement.handler (template-stamp.html:92)
```

I've been isolating the element in a completely empty project and the issue is still there. I checked the examples I noticed it working there. So it's probably an issue with imports.

**Comment by xelra** [comment]
Since this element is deprecated, it's now a dev dependency, which means that the polyfill needs to be explicitly loaded.
```
<script src="bower_components/web-animations-js/web-animations-next-lite.min.js"></script>
```
Importing the `web-animations-next-lite.min.js` polyfill will keep things working for now.

**Comment by GeoloeG-IsT** [comment]
I don't have any direct dependency on `neon-animation` but `paper-tooltip` has, so there is not so much I can do on this one...

**Comment by xelra** [comment]
That is interesting, because `paper-tooltip` is not deprecated. I'll see what I can achieve upstream, but I don't believe this will get fixed any time soon. Because it would require a rewrite of `paper-tooltip`.

Couldn't the polyfill be loaded by `golden-password-input`? So the user is totally unaware?

I think this should be mentioned in the README, because it won't be working for anyone.

**Comment by GeoloeG-IsT** [comment]
https://github.com/PolymerElements/paper-tooltip/issues/121

OK, I'll add the animation polyfill until `paper-tooltip` is fixed

**Comment by GeoloeG-IsT** [comment]
The workaround is in place and presumably working, let's close this for now!
