### ISSUE TITLE
Neon-animation is deprecated

### ISSUE THREAD

**Issue by xelra** [MeTaNoV/gold-password-input#33]
This is probably related to #32.

> ⚠️ This Element is now deprecated ⚠️
> Please use the web animations api or CSS animations
> Web animations polyfill is now a dev dependency

While researching the neon-animation warning, I stumbled across this deprecation notice. It would be great if gold-password-input could use the web animations api instead, as suggested.

**Comment by GeoloeG-IsT** [comment]
Same as previous issue. Let's focus on making `paper-tooltip` great again! :)
