### ISSUE TITLE
2px more vertical height with reveal icon

### ISSUE THREAD

**Issue by xelra** [MeTaNoV/gold-password-input#34]
While creating forms with gold-password-input, I noticed slight asymmetries in my forms. Upon further inspection, I saw that the gold-password-input is 2px higher than the paper-input. 62px vs 64px.

I tried to identify the exact reason, but I don't think it has anything to do with the sizes of the elements in the Shadow DOM. I rather think it's positioning.

Having a close look, I think that the baseline of the input text is 2px further away from the line. There's a bigger gap.

**Comment by xelra** [comment]
I found the issue. It's with the reveal icon. The reveal icon sizes up the input field, I think by 1px on the bottom and 1px on the top.

**Comment by xelra** [comment]
The solutions I was able to apply in the inspector were to either set the `<span class="suffix">` to 24x24px instead of 26x26px or to set a fixed height of 24px on `<div class="input-wrapper">` and make the reveal icon overflow. I actually think that the latter solution looks better, because it doesn't reduce the size of the reveal icon.

I'm not sure though how to appy these settings via mixin or CSS.

**Comment by GeoloeG-IsT** [comment]
Thanks for spotting this one! :) I fixed it in yet another way.
