### ISSUE TITLE
Strength meter overflows out of bounds

### ISSUE THREAD

**Issue by David-Mulder** [MeTaNoV/gold-password-input#4]
Overflows out of bounds

![image](https://cloud.githubusercontent.com/assets/46602/12690773/31265fa0-c6e6-11e5-8177-69e3ee26b74d.png)

**Comment by GeoloeG-IsT** [comment]
Thx @David-Mulder , I'll take a look in the coming week!

**Comment by GeoloeG-IsT** [comment]
@David-Mulder this is in fact an issue with the `addon`, the same issue appears for `paper-input` char counter and probably error-message: https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-input

**Comment by kreinholt** [comment]
One workaround is to use overflow:hidden. I needed to use it because it was messing with the centering of an element after it. Here's a stackoverflow post about it
http://stackoverflow.com/questions/2159843/how-to-make-div-height-increase-to-include-floated-image

**Comment by GeoloeG-IsT** [comment]
@kreinholt , thanks for the tip, but the issue does come from the `paper-input-container` component. I'll try to file an issue if I find some proper time...
